### ISSUE TITLE
WebComponents.org Q1 2014 Roadmap

### ISSUE THREAD

**Issue by addyosmani** [webcomponents/webcomponents.github.io#26]
- [x] Complete new design for V1
- [x] Complete revised implementation for V1
- [ ] Ship a public release of V1 with announcement post
- [ ] Author 5 best practice articles on element authorship
- [ ] Keep articles and resources page regularly updated
- [x] Implement Bower search for web components on customelements.io, link to it
- [x] Setup and actively main the Twitter and G+ accounts
