### ISSUE TITLE
[content] TODO list for adding upcoming podcasts

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#297]
- [x] [The Return of Bosonic](https://plus.google.com/events/ca97v1q145inr4qp5fl4ta7qg8k)
- [x] [Strand Polymer Elements](https://plus.google.com/events/cqoh5rjbat4d3h6cprffgh5f5sc)
- [x] [Custom Elements & Skate.js](https://plus.google.com/events/c7hnukm4vcih811j04cnok7bvv4)
- [x] [Are Web Components Ready Now?](https://plus.google.com/events/cvehk41rtnl5cj7g0kctfapk6uo)
- [x] [Web Components at Microsoft](https://plus.google.com/events/cc9sp87vc6v481at5kpqt4i0loc)
- [x] [Vaadin Components](https://plus.google.com/events/ccp6g60t2npoak35uu2v7mnc5h0)

**Comment by Nevraeka** [comment]
Updated all :)
